# Generated by Django 5.0.1 on 2024-06-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='deadline',
            new_name='expiration_date',
        ),
    ]
